@startuml Basic Sample
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

System_Ext(external_system, "External System")
System_Boundary(ledger, "The Amazing Ledger") {
    Container(ledger_command_handler, "Command handler", "Golang exporting RPC and Rest APIs", "Allows systems to save transactions related to accounts")
    Container(ledger_query_handler, "Query hanlder", "Golang exporting RPC and Rest APIs", "Allows systems to get the balance and load the history of the accounts")
    ContainerDb(query_database, "Query Database", "Postgres Database", "Reads events related to accounts")
    ContainerDb(command_database, "Command Database", "Postgres Database", "Stores transaction and operations related to accounts")
}

Rel_Back(ledger_command_handler, command_database, "Write operations about the accounts")
Rel_Back(ledger_query_handler, query_database, "Read operations related to the accounts")

Rel(external_system, ledger_command_handler, "Save transactions with operations related to accounts", "HTTPS")
Rel(external_system, ledger_query_handler, "Load balance and operations related to accounts", "HTTPS")

Rel_Neighbor(ledger_command_handler, ledger_query_handler, "Sends events related to accounts")
@enduml
